import React from "react";
import dynamic from "next/dynamic";
import fs from "fs";
import path from "path";

const ApolloSandboxComponent = dynamic(
  () => import("@apollo/sandbox/react").then((mod) => mod.ApolloSandbox),
  { ssr: false },
);

export default function OfflineSandbox({ localSchemaString }) {
  if (process.env.NODE_ENV === "production") return <div>Access Denied</div>;

  return (
    <div
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        width: "100vw",
        height: "100vh",
        margin: 0,
        padding: 0,
        overflow: "hidden",
        zIndex: 99999,
        background: "#121212",
      }}
    >
      <div
        style={{ width: "100%", height: "100%" }}
        className="sandbox-wrapper"
      >
        <ApolloSandboxComponent
          initialSchema={localSchemaString}
          initialEndpoint="/api/graphql"
          settings={{
            "editor.theme": "dark",
            "schema.polling.enable": false,
          }}
          style={{ width: "100%", height: "100%" }}
        />
      </div>

      <style jsx global>{`
        html,
        body,
        #__next {
          width: 100% !important;
          height: 100% !important;
          margin: 0 !important;
          padding: 0 !important;
        }
        /* Targets the internal embedded sandbox iframe wrapper generated by the library */
        .sandbox-wrapper iframe,
        .sandbox-wrapper div,
        embed-sandbox-element {
          height: 100vh !important;
          width: 100vw !important;
          min-height: 100vh !important;
        }
      `}</style>
    </div>
  );
}

export async function getStaticProps() {
  const schemaPath = path.join(process.cwd(), "schema.graphql");
  const localSchemaString = fs.readFileSync(schemaPath, "utf8");
  return { props: { localSchemaString } };
}
